### ISSUE TITLE
 Do we need write a ResNet extractor？

### ISSUE THREAD

**Issue by Johnnytjn** [headacheboy/data-of-multimodal-sarcasm-detection#2]
Traceback (most recent call last):
  File "main.py", line 182, in <module>
    m.trainingProcess()
  File "main.py", line 160, in trainingProcess
    batchX, batchImage, batchWord, batchY = self.texti.nextBatch()
  File "/home/wzh/PycharmProjects/data-of-multimodal-sarcasm-detection/codes/loadData.py", line 119, in nextBatch
    image = np.load(imagePrefix+str(ID)+".npy")
  File "/home/wzh/miniconda3/envs/thomas/lib/python3.6/site-packages/numpy/lib/npyio.py", line 415, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../imageVector2/822588646796775425.npy'

Do we need write a ResNet extractor？

**Comment by headacheboy** [comment]
Yes. 

You can find pre-trained ResNet and other image feature extractor model in Tensorflow Slim / pytorch.

**Comment by Johnnytjn** [comment]
thanks
