### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by ichimichi** [headacheboy/data-of-multimodal-sarcasm-detection#7]
I'm gettting the below exception when executing the main.py script

`
Traceback (most recent call last):

File "main.py", line 181, in <module>
    m = Main()
  File "main.py", line 22, in __init__
    self.texti = loadData.TextIterator(self.batchSize, self.seqLen)
  File "/home/ichimichi/colab/data-of-multimodal-sarcasm-detection/codes/loadData.py", line 25, in __init__
    self.word2id = self.getVocab()
  File "/home/ichimichi/colab/data-of-multimodal-sarcasm-detection/codes/loadData.py", line 48, in getVocab
    return pickle.load(file)
TypeError: a bytes-like object is required, not 'str'
`

**Comment by ichimichi** [comment]
I have resolved the issue
